apiVersion: v2
appVersion: 1.3.5
description: Node-RED is low-code programming for event-driven applications
name: openhab
version: 3.1.0
kubeVersion: ">=1.16.0-0"
keywords:
- openhab
home: https://github.com/openhab
icon: https://avatars.githubusercontent.com/u/1007353?s=200&v=4
sources:
- https://github.com/openhab
#- https://github.com/k8s-at-home/charts/tree/master/charts/node-red
maintainers:
- name: skogstorpet
  email: kristerstroemberg@yahoo.se
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.0.0


